DYJetsToLL0to50:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-0To50_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
DYJetsToLL50to100:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-50To100_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
DYJetsToLL100to250:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
DYJetsToLL250to400:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-250To400_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
DYJetsToLL400to650:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-400To650_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
DYJetsToLL650toInf:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-650ToInf_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
DYJetsToLL_Inc:
  pieces:
  - /DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
ZJet_amcatnlo_ptBinned_IncStitch:
  pieces:
  - DYJetsToLL0to50
  - DYJetsToLL50to100
  - DYJetsToLL100to250
  - DYJetsToLL250to400
  - DYJetsToLL400to650
  - DYJetsToLL650toInf
  - DYJetsToLL_Inc
  save: true
    #WWto4Q:
    #pieces:
    #- /WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WWto1L1Nu2Q:
  pieces:
  - /WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WWto2L2Nu:
  pieces:
  - /WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
WW_nlo:
  pieces:
    #- WWto4Q
  - WWto2L2Nu
  - WWto1L1Nu2Q
ZZto2Q2L:
  pieces:
  - /ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
#ZZto2Nu2Q:
  #pieces:
  #- /ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
ZZto4L:
  pieces:
  - /ZZTo4L_TuneCP5_13TeV_powheg_pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
ZZto2L2Nu:
  pieces:
  - /ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
ZZ_nlo:
  pieces:
  - ZZto2Q2L
    #- ZZto2Nu2Q
  - ZZto4L
  - ZZto2L2Nu
WZto1L1Nu2Q:
  pieces:
  - /WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WZto1L3Nu:
  pieces:
  - /WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WZto2Q2L:
  pieces:
  - /WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
WZto3LNu_amcatnlo:
  pieces:
  - /WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
WZto3LNu_powheg:
  pieces:
  - /WZTo3LNu_mllmin4p0_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
WZ_nlo:
  pieces:
  - WZto1L1Nu2Q
  - WZto1L3Nu
  - WZto2Q2L
  #- WZto3LNu_amcatnlo
  - WZto3LNu_powheg
DIBOSON_nlo:
  pieces:
  - WW_nlo
  - ZZ_nlo
  - WZ_nlo
  save: true
TTto2L2Nu:
  pieces:
  - /TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
TTtoHadronic:
  pieces:
  - /TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
TTtoSemiLeptonic:
  pieces:
  - /TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
TTBar_powheg:
  pieces:
  - TTto2L2Nu
  - TTtoHadronic
  - TTtoSemiLeptonic
  save: true
ST_tW_top:
  pieces:
  - /ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
ST_tW_antitop:
  pieces:
  - /ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
ST_t-channel_top:
  pieces:  
  - /ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
ST_t-channel_antitop:
  pieces:
  - /ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
ST_s-channel:
  pieces:
  - /ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
SingleTop:
  pieces:
  - ST_tW_top
  - ST_tW_antitop
  - ST_t-channel_top
  - ST_t-channel_antitop
  - ST_s-channel
  save: true
WJetHT100to200:
  pieces:
  - /WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WJetHT1200to2500:
  pieces:
  - /WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WJetHT200to400:
  pieces:
  - /WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WJetHT2500toInf:
  pieces:
  - /WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
WJetHT400to600:
  pieces:
  - /WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WJetHT600to800:
  pieces:
  - /WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WJetHT70to100:
  pieces:
  - /WJetsToLNu_HT-70To100_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WJetHT800to1200:
  pieces:
  - /WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v3/NANOAODSIM
WJet_HTBinned:
  pieces:
  - WJetHT70to100
  - WJetHT100to200
  - WJetHT200to400
  - WJetHT400to600
  - WJetHT600to800
  - WJetHT800to1200
  - WJetHT1200to2500
  - WJetHT2500toInf
  save: true
WJet_madgraph_Inc:
  pieces:
  - /WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
  save: true
WJet_HTBinned_IncStitch:
  pieces:
  - WJetHT70to100
  - WJetHT100to200
  - WJetHT200to400
  - WJetHT400to600
  - WJetHT600to800
  - WJetHT800to1200
  - WJetHT1200to2500
  - WJetHT2500toInf
  - WJet_madgraph_Inc
  save: true
    #WJet_amcatnlo_0Jet:
    #pieces:
    #- /WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WJet_amcatnlo_1Jet:
  pieces:
  - /WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
WJet_amcatnlo_2Jet:
  pieces:
  - /WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
WJet_amcatnlo_jetBinned:
  pieces:
  - WJet_amcatnlo_1Jet
  - WJet_amcatnlo_2Jet
  save: true
WJetSherpa:
  pieces:
  - /WJetsToLNu_012JetsNLO_34JetsLO_EWNLOcorr_13TeV-sherpa/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
    #  - /WJetsToLNu_012JetsNLO_34JetsLO_EWNLOcorr_13TeV-sherpa/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v1/NANOAODSIM
  save: true
    #WWW:
    #pieces:
    #- /WWW_4F_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v2/NANOAODSIM
    #WWZ:
    #pieces:
    #- /WWZ_4F_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v2/NANOAODSIM
    #WZZ:
    #pieces:
    #- /WZZ_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v2/NANOAODSIM
    #ZZZ:
    #pieces:
    #- /ZZZ_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v2/NANOAODSIM
    #TRIBOSON:
    #pieces:
    #- WWW
    #- WWZ
    #- WZZ
    #- ZZZ
    #save: true
    #TTWtoLNu:
    #pieces:
    #- /TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
    #TTWtoQQ:
    #pieces:
    #- /TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
    #TTZ:
    #pieces:
    #- /ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v2/NANOAODSIM
    #TTX:
    #pieces:
    #- TTWtoLNu
    #- TTWtoQQ
    #- TTZ
    #save: true
GJets100to200:
  pieces:
  - /GJets_DR-0p4_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
GJets200to400:
  pieces:
  - /GJets_DR-0p4_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
GJets400to600:
  pieces:
  - /GJets_DR-0p4_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
GJets600toInf:
  pieces:
  - /GJets_DR-0p4_HT-600ToInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
GJets:
  pieces:
  - GJets100to200
  - GJets200to400
  - GJets400to600
  - GJets600toInf
  save: true
G1Jet_pT50To100:
  pieces:
  - /G1Jet_LHEGpT-50To100_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
G1Jet_pT100To150:
  pieces:
  - /G1Jet_LHEGpT-100To150_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
G1Jet_pT150To250:
  pieces:
  - /G1Jet_LHEGpT-150To250_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
    #  - /G1Jet_LHEGpT-150To250_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v1/NANOAODSIM
G1Jet_pT250To400:
  pieces:
  - /G1Jet_LHEGpT-250To400_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
    #  - /G1Jet_LHEGpT-250To400_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v1/NANOAODSIM
G1Jet_pT400To675:
  pieces:
  - /G1Jet_LHEGpT-400To675_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
    #  - /G1Jet_LHEGpT-400To675_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v1/NANOAODSIM
G1Jet_pT675ToInf:
  pieces:
  - /G1Jet_LHEGpT-675ToInf_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9-v1/NANOAODSIM
    #  - /G1Jet_LHEGpT-675ToInf_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL17NanoAODv9-106X_mc2017_realistic_v9_ext1-v1/NANOAODSIM
GJets_amcatnlo:
  pieces:
  - G1Jet_pT50To100
  - G1Jet_pT100To150
  - G1Jet_pT150To250
  - G1Jet_pT250To400
  - G1Jet_pT400To675
  - G1Jet_pT675ToInf
  save: true
ALLBKG_ZJet_amcatnlo_WJetHT:
  pieces:
  - ZJet_amcatnlo_ptBinned_IncStitch
  - WJet_HTBinned
  - TTBar_powheg
  - SingleTop
  - GJets
  - DIBOSON_nlo
  #- TRIBOSON
  #- TTX
  save: true
    #SinglePhotonB:
    #pieces:
    #- /SinglePhoton/Run2017B-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SinglePhotonC:
    #pieces:
    #- /SinglePhoton/Run2017C-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SinglePhotonD:
    #pieces:
    #- /SinglePhoton/Run2017D-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SinglePhotonE:
    #pieces:
    #- /SinglePhoton/Run2017E-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SinglePhotonF:
    #pieces:
    #- /SinglePhoton/Run2017F-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SinglePhoton_DATA:
    #pieces:
    #- SinglePhotonB
    #- SinglePhotonC
    #- SinglePhotonD
    #- SinglePhotonE
    #- SinglePhotonF
    #isMC: false
    #save: true
    #SingleEleB:
    # pieces:
    #- /SingleElectron/Run2017B-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SingleEleC:
    #pieces:
    #- /SingleElectron/Run2017C-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SingleEleD:
    # pieces:
    # - /SingleElectron/Run2017D-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SingleEleE:
    # pieces:
    #- /SingleElectron/Run2017E-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SingleEleF:
    #pieces:
    #- /SingleElectron/Run2017F-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
    #SingleElectron_DATA:
    # pieces:
    # - SingleEleB
    # - SingleEleC
    # - SingleEleD
    # - SingleEleE
    #- SingleEleF
    #isMC: false
    #save: true
DoubleEG_B:
  pieces:
  - /DoubleEG/Run2017B-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
DoubleEG_C:
  pieces:
  - /DoubleEG/Run2017C-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
DoubleEG_D:
  pieces:
  - /DoubleEG/Run2017D-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
DoubleEG_E:
  pieces:
  - /DoubleEG/Run2017E-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
DoubleEG_F:
  pieces:
  - /DoubleEG/Run2017F-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
DoubleEG_DATA:
  pieces:
  - DoubleEG_B
  - DoubleEG_C
  - DoubleEG_D
  - DoubleEG_E
  - DoubleEG_F
  isMC: false
  save: true
QCDFakes_DATA:
  pieces:
    #- SinglePhoton_DATA
    #- SingleElectron_DATA
  - DoubleEG_DATA
  isMC: false
  save: true
