#QCDFakes_SinglePhoton_2016B_v1:
  #pieces:
  #- /SinglePhoton/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016B_v2:
  #pieces:
  #- /SinglePhoton/Run2016B-ver2_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016C:
  #pieces:
  #- /SinglePhoton/Run2016C-HIPM_UL2016_MiniAODv2_NanoAODv9-v4/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016D:
  #pieces:
  #- /SinglePhoton/Run2016D-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016E:
  #pieces:
  #- /SinglePhoton/Run2016E-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016F:
  #pieces:
  #- /SinglePhoton/Run2016F-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton:
  #pieces:
  #- QCDFakes_SinglePhoton_2016B_v1
  #- QCDFakes_SinglePhoton_2016B_v2
  #- QCDFakes_SinglePhoton_2016C
  #- QCDFakes_SinglePhoton_2016D
  #- QCDFakes_SinglePhoton_2016E
  #- QCDFakes_SinglePhoton_2016F
  #isMC: false
  #save: true
  #QCDFakes_SingleEle_2016B_v1:
  #pieces:
  #- /SingleElectron/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #QCDFakes_SingleEle_2016B_v2:
  #pieces:
  #- /SingleElectron/Run2016B-ver2_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #QCDFakes_SingleEle_2016C:
  #pieces:
  # - /SingleElectron/Run2016C-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #QCDFakes_SingleEle_2016D:
  #pieces:
  #- /SingleElectron/Run2016D-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #QCDFakes_SingleEle_2016E:
  #pieces:
  #- /SingleElectron/Run2016E-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #QCDFakes_SingleEle_2016F:
  #pieces:
  #- /SingleElectron/Run2016F-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #QCDFakes_SingleEle:
  #pieces:
  #- QCDFakes_SingleEle_2016B_v1
  #- QCDFakes_SingleEle_2016B_v2
  #- QCDFakes_SingleEle_2016C
  #- QCDFakes_SingleEle_2016D
  #- QCDFakes_SingleEle_2016E
  #- QCDFakes_SingleEle_2016F
  #isMC: false
  #save: true
QCDFakes_DoubleEG_B_v1:
  pieces:
  - /DoubleEG/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG_B_v2:
  pieces:
  - /DoubleEG/Run2016B-ver2_HIPM_UL2016_MiniAODv2_NanoAODv9-v3/NANOAOD
QCDFakes_DoubleEG_C:
  pieces:
  - /DoubleEG/Run2016C-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG_D:
  pieces:
  - /DoubleEG/Run2016D-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG_E:
  pieces:
  - /DoubleEG/Run2016E-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG_F:
  pieces:
  - /DoubleEG/Run2016F-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG:
  pieces:
  - QCDFakes_DoubleEG_B_v1
  - QCDFakes_DoubleEG_B_v2
  - QCDFakes_DoubleEG_C
  - QCDFakes_DoubleEG_D
  - QCDFakes_DoubleEG_E
  - QCDFakes_DoubleEG_F
  isMC: false
  save: true
QCDFakes_DATA:
  pieces:
    #- QCDFakes_SinglePhoton
    #- QCDFakes_SingleEle
  - QCDFakes_DoubleEG
  isMC: false
  save: true
