DYJetsToLL_0To50:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-0To50_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
DYJetsToLL_50To100:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-50To100_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
DYJetsToLL_100To250:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-100To250_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
DYJetsToLL_250To400:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-250To400_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
DYJetsToLL_400To650:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-400To650_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
DYJetsToLL_650ToInf:
  pieces:
  - /DYJetsToLL_LHEFilterPtZ-650ToInf_MatchEWPDG20_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
DYJetsToLL_Inc:
  pieces:
  - /DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
  save: true
#DYJetsToLL_madgraph:
#  pieces:
#  - /DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#DYJetsToLL_powheg:
#  pieces:
#  - /DYJetsToEE_M-50_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
ZJet_amcatnlo_ptBinned:
  pieces:
  - DYJetsToLL_0To50
  - DYJetsToLL_50To100
  - DYJetsToLL_100To250
  - DYJetsToLL_250To400
  - DYJetsToLL_400To650
  - DYJetsToLL_650ToInf
  save: true
ZJet_amcatnlo_ptBinned_IncStitch:
  pieces:
  - ZJet_amcatnlo_ptBinned
  - DYJetsToLL_Inc
  save: true
#ZJetNNLO_10to50:
#  pieces:
#  - /DYJetsToEE_M-10to50_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_100to200:
#  pieces:
#  - /DYJetsToEE_M-100to200_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_200to400:
#  pieces:
#  - /DYJetsToEE_M-200to400_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_400to500:
#  pieces:
#  - /DYJetsToEE_M-400to500_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_500to700:
#  pieces:
#  - /DYJetsToEE_M-500to700_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_700to800:
#  pieces:
#  - /DYJetsToEE_M-700to800_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_800to1000:
#  pieces:
#  - /DYJetsToEE_M-800to1000_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_1000to1500:
#  pieces:
#  - /DYJetsToEE_M-1000to1500_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_1500to2000:
#  pieces:
#  - /DYJetsToEE_M-1500to2000_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_2000toInf:
#  pieces:
#  - /DYJetsToEE_M-2000toInf_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_Inc:
#  pieces:
#  - /DYJetsToEE_M-50_massWgtFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZJetNNLO_IncStitch:
#  pieces:
#  - ZJetNNLO_10to50
#  - ZJetNNLO_100to200
#  - ZJetNNLO_200to400
#  - ZJetNNLO_400to500
#  - ZJetNNLO_500to700
#  - ZJetNNLO_700to800
#  - ZJetNNLO_800to1000
#  - ZJetNNLO_1000to1500
#  - ZJetNNLO_1500to2000
#  - ZJetNNLO_2000toInf
#  - ZJetNNLO_Inc
#  save: true
#WWTo4Q_4f:
#  pieces:
#  - /WWTo4Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v3/NANOAODSIM
WWTo1L1Nu2Q_4f:
  pieces:
  - /WWTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WWTo2L2Nu:
  pieces:
  - /WWTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WW_nlo:
  pieces:
  - WWTo2L2Nu
  - WWTo1L1Nu2Q_4f
  save: true
ZZTo2Q2L:
  pieces:
  - /ZZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
ZZTo4L:
  pieces:
  - /ZZTo4L_TuneCP5_13TeV_powheg_pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
#ZZTo2Nu2Q_5f:
#  pieces:
#  - /ZZTo2Nu2Q_5f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
ZZTo2L2Nu:
  pieces:
  - /ZZTo2L2Nu_TuneCP5_13TeV_powheg_pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
ZZ_nlo:
  pieces:
  - ZZTo2Q2L
  - ZZTo4L
#  - ZZTo2Nu2Q_5f
  - ZZTo2L2Nu
  save: true
WZTo1L1Nu2Q_4f:
  pieces:
  - /WZTo1L1Nu2Q_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WZTo1L3Nu_4f:
  pieces:
  - /WZTo1L3Nu_4f_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WZTo2Q2L_mllmin4p0:
  pieces:
  - /WZTo2Q2L_mllmin4p0_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
WZTo3LNu:
  pieces:
  - /WZTo3LNu_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WZTo3LNu_mllmin4p0:
  pieces:
  - /WZTo3LNu_mllmin4p0_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WZ_nlo:
  pieces:
  - WZTo1L1Nu2Q_4f
  - WZTo1L3Nu_4f
  - WZTo2Q2L_mllmin4p0
  - WZTo3LNu
  save: true
DIBOSON_nlo:
  pieces:
  - WW_nlo
  - ZZ_nlo
  - WZ_nlo
  save: true
TTTo2L2Nu:
  pieces:
  - /TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
TTToHadronic:
  pieces:
  - /TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
TTToSemiLeptonic:
  pieces:
  - /TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
TTBar_powheg:
  pieces:
  - TTTo2L2Nu
  - TTToHadronic
  - TTToSemiLeptonic
  save: true
ST_tW_top_5f:
  pieces:
  - /ST_tW_top_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
ST_tW_antitop_5f:
  pieces:
  - /ST_tW_antitop_5f_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
ST_t-channel_antitop_5f:
  pieces:
  - /ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
ST_t-channel_top_5f:
  pieces:
  - /ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
ST_s-channel_4f:
  pieces:
  - /ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
SingleTop:
  pieces:
  - ST_tW_top_5f
  - ST_tW_antitop_5f
  - ST_t-channel_antitop_5f
  - ST_s-channel_4f
  save: true
#WJetsToLNu_0J:
#  pieces:
#  - /WJetsToLNu_0J_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WJetsToLNu_1J:
  pieces:
  - /WJetsToLNu_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WJetsToLNu_2J:
  pieces:
  - /WJetsToLNu_2J_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WJet_amcatnlo_Inc:
  pieces:
  - /WJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
  save: true
WJet_amcatnlo_jetBinned:
  pieces:
#  - WJetsToLNu_0J
  - WJetsToLNu_1J
  - WJetsToLNu_2J
  save: true
#WJet_amcatnlo_jetBinned_lte1Jet:
#  pieces:
#  - WJetsToLNu_0J
#  - WJetsToLNu_1J
#  save: true
WJetHT70To100:
  pieces:
  - /WJetsToLNu_HT-70To100_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM
WJetHT100To200:
  pieces:
  - /WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM
WJetHT200To400:
  pieces:
  - /WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM
WJetHT400To600:
  pieces:
  - /WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM
WJetHT600To800:
  pieces:
  - /WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM
WJetHT800To1200:
  pieces:
  - /WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM
WJetHT1200To2500:
  pieces:
  - /WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM
WJetHT2500ToInf:
  pieces:
  - /WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v2/NANOAODSIM
WJet_HTBinned:
  pieces:
  - WJetHT100To200
  - WJetHT200To400
  - WJetHT400To600
  - WJetHT600To800
  - WJetHT800To1200
  - WJetHT1200To2500
  - WJetHT2500ToInf
  save: true
WJetMadgraphInc:
  pieces:
  - /WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
WJet_HTBinned_IncStitch:
  pieces:
  - WJet_HTBinned
  - WJetMadgraphInc
  save: true
WJetSherpa:
  pieces:
  - /WJetsToLNu_012JetsNLO_34JetsLO_EWNLOcorr_13TeV-sherpa/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM
  save: true
    #WWW_4F:
    #pieces:
    #- /WWW_4F_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11_ext1-v1/NANOAODSIM
    #WWZ_4F:
    #pieces:
    #- /WWZ_4F_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11_ext1-v1/NANOAODSIM
    #WZZ:
    #pieces:
    #- /WZZ_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11_ext1-v1/NANOAODSIM
    #ZZZ:
    #pieces:
    #- /ZZZ_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11_ext1-v1/NANOAODSIM
    #TRIBOSON:
    #pieces:
    #- WWW_4F
    #- WWZ_4F
    #- WZZ
    #- ZZZ
    #save: true
    #TTWJetsToLNu:
    #pieces:
    #- /TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
    #TTWJetsToQQ:
    #pieces:
    #- /TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
    #TTW:
    #pieces:
    #- TTWJetsToLNu
    #- TTWJetsToQQ
    #save: true
    #TTZ:
    #pieces:
    #- /ttZJets_TuneCP5_13TeV_madgraphMLM_pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
GJets_100To200:
  pieces:
  - /GJets_DR-0p4_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
GJets_200To400:
  pieces:
  - /GJets_DR-0p4_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
GJets_400To600:
  pieces:
  - /GJets_DR-0p4_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
GJets_600ToInf:
  pieces:
  - /GJets_DR-0p4_HT-600ToInf_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v2/NANOAODSIM
GJets:
  pieces:
  - GJets_100To200
  - GJets_200To400
  - GJets_400To600
  - GJets_600ToInf
  save: true
G1Jets_pT50To100:
  pieces:
  - /G1Jet_LHEGpT-50To100_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
G1Jets_pT100To150:
  pieces:
  - /G1Jet_LHEGpT-100To150_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
G1Jets_pT150To250:
  pieces:
  - /G1Jet_LHEGpT-150To250_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
    #  - /G1Jet_LHEGpT-150To250_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11_ext1-v1/NANOAODSIM
G1Jets_pT250To400:
  pieces:
  - /G1Jet_LHEGpT-250To400_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
    #  - /G1Jet_LHEGpT-250To400_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11_ext1-v1/NANOAODSIM
G1Jets_pT400To675:
  pieces:
  - /G1Jet_LHEGpT-400To675_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
    #  - /G1Jet_LHEGpT-400To675_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11_ext1-v1/NANOAODSIM
G1Jets_pT675ToInf:
  pieces:
  - /G1Jet_LHEGpT-675ToInf_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11-v1/NANOAODSIM
    #  - /G1Jet_LHEGpT-675ToInf_TuneCP5_13TeV-amcatnlo-pythia8/RunIISummer20UL16NanoAODAPVv9-106X_mcRun2_asymptotic_preVFP_v11_ext1-v1/NANOAODSIM
GJets_amcatnlo:
  pieces:
  - G1Jets_pT50To100
  - G1Jets_pT100To150
  - G1Jets_pT150To250
  - G1Jets_pT250To400
  - G1Jets_pT400To675
  - G1Jets_pT675ToInf
  save: true
#OTHERBKG_WJetAMCJetBinned_dibosonNLO_triboson:
#  pieces:
#  - WJet_amcatnlo_jetBinned
#  - SingleTop
#  - DIBOSON_nlo
#  - TRIBOSON
#  - TTW
#  - TTZ
#  - PhotonJets_Madgraph
#  save: true
#ALLBKG_powhegTTBar_ZJetPtWJetAMCJetBinned_NLODIBOSON_triboson:
#  pieces:
#  - ZJet_amcatnlo_ptBinned
#  - TTbar_powheg
#  - WJet_amcatnlo_jetBinned
#  - SingleTop
#  - DIBOSON_nlo
#  - TRIBOSON
#  - TTW
#  - TTZ
#  - PhotonJets_Madgraph
#  save: true
ALLBKG_ZJet_amcatnlo_WJetHT:
  pieces:
  - ZJet_amcatnlo_ptBinned_IncStitch
  - TTBar_powheg
  - WJet_HTBinned
  - SingleTop
  - DIBOSON_nlo
#  - TRIBOSON
#  - TTW
#  - TTZ
  - GJets
  save: true
#QCDFakes_SinglePhoton_2016B_v1:
  #pieces:
  #- /SinglePhoton/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016B_v2:
  #pieces:
  #- /SinglePhoton/Run2016B-ver2_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016C:
  #pieces:
  #- /SinglePhoton/Run2016C-HIPM_UL2016_MiniAODv2_NanoAODv9-v4/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016D:
  #pieces:
  #- /SinglePhoton/Run2016D-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016E:
  #pieces:
  #- /SinglePhoton/Run2016E-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton_2016F:
  #pieces:
  #- /SinglePhoton/Run2016F-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
  #isMC: false
  #QCDFakes_SinglePhoton:
  #pieces:
  #- QCDFakes_SinglePhoton_2016B_v1
  #- QCDFakes_SinglePhoton_2016B_v2
  #- QCDFakes_SinglePhoton_2016C
  #- QCDFakes_SinglePhoton_2016D
  #- QCDFakes_SinglePhoton_2016E
  #- QCDFakes_SinglePhoton_2016F
  #isMC: false
  #save: true
    #QCDFakes_SingleEle_2016B_v1:
    #pieces:
    #- /SingleElectron/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
    #QCDFakes_SingleEle_2016B_v2:
    #pieces:
    #- /SingleElectron/Run2016B-ver2_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
    #QCDFakes_SingleEle_2016C:
    # pieces:
    # - /SingleElectron/Run2016C-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
    #QCDFakes_SingleEle_2016D:
    # pieces:
    #- /SingleElectron/Run2016D-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
    #QCDFakes_SingleEle_2016E:
    #pieces:
    #- /SingleElectron/Run2016E-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
    #QCDFakes_SingleEle_2016F:
    # pieces:
    #- /SingleElectron/Run2016F-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
    #QCDFakes_SingleEle:
    #pieces:
    # - QCDFakes_SingleEle_2016B_v1
    # - QCDFakes_SingleEle_2016B_v2
    # - QCDFakes_SingleEle_2016C
    # - QCDFakes_SingleEle_2016D
    # - QCDFakes_SingleEle_2016E
    # - QCDFakes_SingleEle_2016F
    #isMC: false
    #save: true
QCDFakes_DoubleEG_B_v1:
  pieces:
  - /DoubleEG/Run2016B-ver1_HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG_B_v2:
  pieces:
  - /DoubleEG/Run2016B-ver2_HIPM_UL2016_MiniAODv2_NanoAODv9-v3/NANOAOD
QCDFakes_DoubleEG_C:
  pieces:
  - /DoubleEG/Run2016C-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG_D:
  pieces:
  - /DoubleEG/Run2016D-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG_E:
  pieces:
  - /DoubleEG/Run2016E-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG_F:
  pieces:
  - /DoubleEG/Run2016F-HIPM_UL2016_MiniAODv2_NanoAODv9-v2/NANOAOD
QCDFakes_DoubleEG:
  pieces:
  - QCDFakes_DoubleEG_B_v1
  - QCDFakes_DoubleEG_B_v2
  - QCDFakes_DoubleEG_C
  - QCDFakes_DoubleEG_D
  - QCDFakes_DoubleEG_E
  - QCDFakes_DoubleEG_F
  isMC: false
  save: true
QCDFakes_DATA:
  pieces:
    #- QCDFakes_SinglePhoton
    #- QCDFakes_SingleEle
  - QCDFakes_DoubleEG
  isMC: false
  save: true
